### ISSUE TITLE
팥알님의 신세벌 P2 자판 추가 부탁드려 봅니다

### ISSUE THREAD

**Issue by soomtong** [3beol/libhangul#12]
안녕하세요!

팥알님의 신세벌식 P2 나온지 시간이 조금 되어 어느 정도 안정된 상태라 생각되어 
이렇게 부탁드려 봅니다.

감사합니다.
새해 복 많이 받으세요!

**Comment by 3beol** [comment]
신세벌식 P2 는 적용되어 있습니다.

soomtong 님께서도 새해 복 많이 받으세요.
