### ISSUE TITLE
3-P3 자판의 ㅡ+ㅣ→ㅢ 조합

### ISSUE THREAD

**Issue by pat-al** [3beol/libhangul#6]
안녕하세요? 3-P3 자판을 넣어 주셔서 감사 드립니다.

3-P3 자판에서 오른손 쪽에서 ㅡ를 치고 왼손 쪽에서 ㅣ를 쳤을 때 '의' 꼴이 아닌 '읗' 꼴로 들어갑니다.
세벌식 사랑 모임에서 다른 분이 말씀해 주셔서 알게 되었습니다.
수정 부탁 드립니다.

**Comment by 3beol** [comment]
고쳐서 올렸습니다.

**Comment by pat-al** [comment]
ㅢ 조합이 잘 되는 걸 확인했습니다.
고맙습니다. ^^
