### ISSUE TITLE
팥알님의 3-P2 자판도 추가해주실 수 있으신지요

### ISSUE THREAD

**Issue by soomtong** [3beol/libhangul#9]
안녕하세요!

2012 쓰다 2015 쓰면서 팥알3-P2 로 옮기고 싶은데 3-P3 는 있는데 2가 없어서 문의 드립니다.
추가 가능하시면 부탁드릴께요 :)

**Comment by 3beol** [comment]
네 알겠습니다

**Comment by 3beol** [comment]
3-p2 를 넣었습니다.

**Comment by soomtong** [comment]
3-P2 가 포함된 버전을 등록했습니다. 감사합니다.
https://github.com/soomtong/gureum/releases/tag/GureumKIM-1.9.1
